config/routes.rb
Harena::Application.routes.draw do

  devise_for :players, :controllers => { :registrations => "registrations" }

  namespace :api, :defaults => { :format => :json } do

    resources :tournaments, except: [:new, :edit]
    post  '/tournaments/:id/start',    to: 'tournaments#start'
    post  '/tournaments/:id/register', to: 'tournaments#register'
    patch '/tournaments/:id/accept',   to: 'tournaments#accept'
    
    resources :matches, only: [:show, :update]
  end

  root :to => "home#index"

end

app/views/layouts/_navigation.slim
.navbar.navbar-default.navbar-static-top.navbar-inverse role="navigation"
  .container
    .navbar-header
      button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
      = link_to "Hero Academy Arena", root_path, :class => 'navbar-brand'
    .navbar-collapse.collapse
      ul.nav.navbar-nav
        li
          a href="http://forums.robotentertainment.com/forumdisplay.php?121-Hero-Academy-General-Discussion" target="_blank" Forum
        li
          a href="http://www.robotentertainmentfans.com/fans/groups/hero-academy-league/" target="_blank" League
      ul.nav.navbar-nav.navbar-right
        - if signed_in?
          li class=active_if_current(edit_player_registration_path)
            = link_to current_player.username, edit_player_registration_path
          li
            = link_to "Sign out", destroy_player_session_path, method: :delete
        - else
          li class=active_if_current(new_player_registration_path)
            = link_to "Sign up", new_player_registration_path
          li class=active_if_current(new_player_session_path)
            = link_to "Sign in", new_player_session_path

app/views/layouts/application.slim
doctype html
html ng-app="Harena"
  head
    title Harena
    meta charset="utf-8"
    
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

    /! HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    /! WARNING: Respond.js doesn't work if you view the page via file://
    /![if lt IE 9]
      | <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      | <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>

  body
    = render "layouts/navigation"
    = yield
    footer
      .container
        hr.featurette-divider
        .row
          .col-lg-6
            p
              | Developed by 
              a href="mailto:warloktus@gmail.com" Warloktus
              | .
          .col-lg-6
            p.text-right
              | Consider 
              a href="#" buying me beers
              |  to keep me working on this.